name: Linux Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, aarch64]
          
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v1          
      - name: Build wheels
        env:
          CIBW_ARCHS: ${{matrix.arch}}
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
          CIBW_SKIP: '*-musllinux*'
          CIBW_BEFORE_BUILD: yum install -y libcurl-devel && pip install -r requirements-dev.txt
        run: |
          python -m pip install --upgrade pip setuptools
          pip install cibuildwheel
          cibuildwheel --output-dir dist
        shell: bash
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
